site_name: ID Solutions
site_url: https://radlovacki.github.io/id_solutions/
site_author: ID Solutions Team
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: white
    accent: indigo
  language: sr
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
copyright: Copyright &copy; 2025 ID Solutions

nav:
  - Почетна: index.md
  - О нама:
    - Компанија: about/index.md
    - Програм: about/program.md
  - База знања:
    - RFID и NFC: knowledge/index.md
    - Непрограмабилни нискофреквентни RFID чипови: knowledge/lf_ro_rfid.md
    - Програмабилни нискофреквентни RFID чипови: knowledge/lf_rw_rfid.md
    - MIFARE Classic: knowledge/mifare_classic.md
    - NFC: knowledge/nfc.md
    - NTAG: knowledge/ntag.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox

hooks:
  - docs/assets/socialmedia.py

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/radlovacki/id_solutions
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/id.solutions.vrsac/
  generator: false

extra_javascript:
  - assets/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
